### ISSUE TITLE
hyperparameter importance

### ISSUE THREAD

**Issue by jonaden94** [MCG-NJU/MOTIP#40]
First of all, thank you for your amazing work. I tried it on animal data and it worked quite well out-of-the-box. Unfortunately, the model has so many hyperparameters and I am unsure which of these are important for further improving the model for other domains. Could you provide some guidance on which parameters I should focus on?

Kind regards

**Comment by HELLORPG** [comment]
I'm thrilled to hear that it worked well out-of-the-box. Your feedback is very encouraging. 

Based on my experience, the following hyperparameters may be important:

```yaml
# The max disappearance (miss) tolerance of tracklets:
SAMPLE_LENGTHS: [40]
MAX_TEMPORAL_LENGTH: 40

# Inference thresholds:
ID_THRESH: 0.2
DET_THRESH: 0.3
NEWBORN_THRESH: 0.6

# Training Augmentation, more detailed fine-tuning on specific datasets may yield better results:
TRAJ_DROP_RATIO: 0.5
TRAJ_SWITCH_RATIO: 0.3
```

BTW, may I ask that which configuration file have you employed for your dataset?
